### ISSUE TITLE
employees view for inserting

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#17]
Create a simplified view with list containing name, surname, (mail) and input fields for worktime and vacation pool (with initial data from database, and daily/hourly handling, maybe parsing e.g. 1,5 -> 1 day 5 hours) for quick bulk data inserting.

**Comment by puninup** [comment]
I think we have that view - the "Employees" view.
But I agree that it can look a bit more better and the employee info could be more condensed.
The "parsable" input field for hours it's a good idea, but in my opinion it should work more like "1d 5h" -> 1 day 5 hours, because it's more intuitive (in my opinion) - for example we can write only 5h instead of 0,5.

**Comment by Liczi** [comment]
_Edit after consulting with Ania:_ 
the list item should contain labels: Name, Surname, remaining hours, work time
and inputs: input for **inserting** not overriding days pool, in pattern: 

> The "parsable" input field for hours it's a good idea, but in my opinion it should work more like "1d 5h" -> 1 day 5 hours, because it's more intuitive (in my opinion) - for example we can write only 5h instead of 0,5.

and also work time modification dropdown select list
